// WARNING:
// This code was generated by a tool. DO NOT MODIFY!

`include "obf_defines.v"

module obf_pt2(
    index,
    addr
);

input [`OBF_INDEX_BUS] index;
output reg [`LUT_ADDR_BUS] addr;

always @(index) begin
    case(index)
		`OBF_INDEX_WIDTH'd24: addr = `LUT_ADDR_WIDTH'd1;
		`OBF_INDEX_WIDTH'd25: addr = `LUT_ADDR_WIDTH'd6;
		`OBF_INDEX_WIDTH'd6: addr = `LUT_ADDR_WIDTH'd11;

        default: addr = `LUT_ADDR_WIDTH'd0;
    endcase
end
endmodule
