// WARNING:
// This code was generated by a tool. DO NOT MODIFY!

`include "obf_defines.v"

module obf_lut1(
    addr,
    out_sub,
    out_imm
);

input [`LUT_ADDR_BUS] addr;
output [`LUT_OUT_BUS] out_sub;
output [`LUT_OUT_BUS] out_imm;

wire [`LUT_OUT_BUS] lut [0:59];

assign lut[0] = 16'b0000000000000001;
assign lut[1] = 16'b0000000000000000;
assign lut[2] = 16'b0101010010111101;
assign lut[3] = 16'b0000000000000000;
assign lut[4] = 16'b0100001100111101;
assign lut[5] = 16'b0010000010100010;
assign lut[6] = 16'b0101010110011100;
assign lut[7] = 16'b0010000000001010;
assign lut[8] = 16'b0100001100111101;
assign lut[9] = 16'b0000000000000000;
assign lut[10] = 16'b0010000001111111;
assign lut[11] = 16'b0000000000000000;
assign lut[12] = 16'b0010011110011111;
assign lut[13] = 16'b0010000010100010;
assign lut[14] = 16'b0101010100011100;
assign lut[15] = 16'b0010000001101010;
assign lut[16] = 16'b0010000010111111;
assign lut[17] = 16'b0101010011000001;
assign lut[18] = 16'b0000000011111111;
assign lut[19] = 16'b0101011101000000;
assign lut[20] = 16'b0000000000010000;
assign lut[21] = 16'b0101011101001001;
assign lut[22] = 16'b0000000000010000;
assign lut[23] = 16'b0010000110100011;
assign lut[24] = 16'b0000000000000000;
assign lut[25] = 16'b0000000000000001;
assign lut[26] = 16'b0101000110000000;
assign lut[27] = 16'b0101011101001000;
assign lut[28] = 16'b0000000000011000;
assign lut[29] = 16'b0101011101001001;
assign lut[30] = 16'b0000000000011000;
assign lut[31] = 16'b0101001000000000;
assign lut[32] = 16'b0101010011001001;
assign lut[33] = 16'b0000000011111111;
assign lut[34] = 16'b0101001010000000;
assign lut[35] = 16'b0101011101001000;
assign lut[36] = 16'b0000000000010000;
assign lut[37] = 16'b0101011101001001;
assign lut[38] = 16'b0000000000010000;
assign lut[39] = 16'b0101001000000000;
assign lut[40] = 16'b0101010011001001;
assign lut[41] = 16'b1111111111111111;
assign lut[42] = 16'b0101010100001100;
assign lut[43] = 16'b0101011101001001;
assign lut[44] = 16'b0000000000010000;
assign lut[45] = 16'b0000000000000000;
assign lut[46] = 16'b0011100101111111;
assign lut[47] = 16'b0010000010100010;
assign lut[48] = 16'b0101010100011100;
assign lut[49] = 16'b0010000010000010;
assign lut[50] = 16'b0101010010111101;
assign lut[51] = 16'b0000000000000000;
assign lut[52] = 16'b0101011001011101;
assign lut[53] = 16'b0000000000000001;
assign lut[54] = 16'b0000000000000000;
assign lut[55] = 16'b0101010110111101;
assign lut[56] = 16'b0000000000000000;
assign lut[57] = 16'b0101011100111101;
assign lut[58] = 16'b0000000000000000;
assign lut[59] = 16'b0010000100011111;


assign out_sub = lut[addr];
assign out_imm = lut[addr+1];

endmodule
