// WARNING:
// This code was generated by a tool. DO NOT MODIFY!

`include "obf_defines.v"

module obf_lut2(
    addr,
    out_sub,
    out_imm
);

input [`LUT_ADDR_BUS] addr;
output [`LUT_OUT_BUS] out_sub;
output [`LUT_OUT_BUS] out_imm;

wire [`LUT_OUT_BUS] lut [0:16];

assign lut[0] = 16'b0000000000000001;
assign lut[1] = 16'b0101001010000000;
assign lut[2] = 16'b0101011101001000;
assign lut[3] = 16'b0000000000011000;
assign lut[4] = 16'b0101011101001001;
assign lut[5] = 16'b0000000000011000;
assign lut[6] = 16'b0000000000000000;
assign lut[7] = 16'b0101011101001000;
assign lut[8] = 16'b0000000000010000;
assign lut[9] = 16'b0101011101001001;
assign lut[10] = 16'b0000000000010000;
assign lut[11] = 16'b0101010101011100;
assign lut[12] = 16'b0000000000000001;
assign lut[13] = 16'b0101011101011100;
assign lut[14] = 16'b0000000000010000;
assign lut[15] = 16'b0101011000001100;
assign lut[16] = 16'b0010000010111111;


assign out_sub = lut[addr];
assign out_imm = lut[addr+1];

endmodule
